# configservers.yaml

db-servers: 
    - #test target server
        name: "test_target_server"
        environment: "test"
        host: "192.168.1.141"
        port: 5433
        user: "${METRICS_TEST_DB_USER}"
        password: "${METRICS_TEST_DB_PASSWORD}"
        DbName: "application"